### ISSUE TITLE
Monorepo, setup-node action fails

### ISSUE THREAD

**Issue by CODE-MNA** [CODE-MNA/RoomChat#3]
Action setup-node@v3 isn't able to run and you get the error package-lock.json not found.
This happens in the monorepo folder structure.

### Fix:
add cache-dependancy-path property in the step. (PACKAGE_DIR variable points to the directory of the package you trying to build.

```yaml

name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{vars.PACKAGE_DIR}}/package-lock.json
```
